config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :books
    resources :borrows
  end
  resources :books
  resources :users
  resources :borrows
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
  belongs_to :publisher
  has_many :borrows
  validates :author_id, presence: true
  validates :category_id, presence: true
  validates :publisher_id, presence: true
  validates :name, presence: true
  validates :image, presence:true
  validates :page, presence:true
  validates :description, presence: true, length: {maximum: Settings.book.validates.description_maximum}

  scope :load_by_order, ->{order "created_at DESC"}
end

app/models/borrow.rb
class Borrow < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :book_id, presence: true
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy

  scope :load_data, ->{select(:id, :name)}
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :destroy

  scope :load_data, ->{select(:id, :name)}
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/return.rb
class Return < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :borrows, dependent: :destroy
  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: Settings.user.validates.name_maximum}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.user.validates.email_maximum},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: Settings.user.validates.password_minimum}

  scope :load_data, ->{select("fullname, phone")}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def current_user? user
    user == current_user
  end

  def remember
    self.remember_token = User.new_token
    update_attributes :remember_digest, User.digest(remember_token)
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new remember_digest.is_password?(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find_by id: params[:id]
    redirect_to root_url if @author.nil?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def index
    @books = Book.paginate page: params[:page], per_page: Settings.books.page
  end

  def show
    @book = Book.find_by id: params[:id]
    redirect_to root_url if @book.nil?
  end

  private

  def book_params
    params.require(:book).permit :content
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]

  def index
    @users = User.select_user.paginate page: params[:page], per_page: Settings.users.page
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by id: params[:id]
    redirect_to root_url if @user.nil?
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t ".success"
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    User.find params[:id].destroy
    flash[:success] = t ".delete_user"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = " "
    base_title = t ".title"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/request_borrow_helper.rb
module RequestBorrowHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="container-fluid" id="footer">
  <small><%= t ".copyright" %></small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), "#" %></li>
      <li><%= link_to t(".contact"), "#" %></li>
      <li><%= link_to t(".news"), "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <div class="navbar-brand"><%= link_to t(".library"), root_path, class:"glyphicon glyphicon-book", id: "logo" %></div>
    </div>
    <form class="navbar-form navbar-left" action="#">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Nhập tên sách, tuyển tập, tác giả,...">
      <div class="input-group-btn">
      <button class="btn btn-default" type="submit">
        <i class="glyphicon glyphicon-search"></i>
      </button>
      </div>
      </div>
    </form>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path, class:"glyphicon glyphicon-home" %></li>
        <li class="dropdown">
          <a class="dropdown-toggle glyphicon glyphicon-menu-hamburger" data-toggle="dropdown" href="#">
            <%= t ".categories" %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
            <li role="presentation" class="dropdown-header">
              <%= link_to t(".audio_book"), "#" %>
            </li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
              <%= link_to t(".story"),"#" %></a>
            </li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
              <%= link_to t(".life_skill"),"#" %></a>
            </li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
              <%= link_to t(".children's_story"), "#" %></a>
            </li>
            <li role="presentation" class="divider"></li>
            <li role="presentation" class="dropdown-header">
              <%= link_to t(".business"), "#" %>
            </li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
              <%= link_to t(".startup"), "#" %></a>
            </li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
              <%= link_to t(".sales_marketing"), "#" %></a>
            </li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">
              <%= link_to t(".leadership_manager"), "#" %></a>
            </li>
          </ul>
        </li>
        <% if logged_in? %>
          <li><%= link_to t(".user"), users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t ".account" %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t(".profile"), current_user %></li>
                <li><%= link_to t(".setting"), "#" %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t(".logout"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
        <% else %>
          <li><%= link_to t(".login"), login_path, class:"glyphicon glyphicon-user" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidenav.html.erb
<div class="col-sm-3 sidenav hidden-xs">
  <h2><%= t ".management" %></h2>
  <ul class="nav nav-pills nav-stacked">
    <li><%= link_to t(".dashboard"), "#" %></li>
    <li><%= link_to t(".request"), "#" %></li>
    <li><%= link_to t(".user"), "#" %></li>
    <li><%= link_to t(".book"), admin_books_path %></li>
    <li><%= link_to t(".author"), "#" %></li>
  </ul>
</div>

app/views/layouts/_slides.html.erb
<div class="container-fluid">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="https://images-na.ssl-images-amazon.com/images/G/01/US-hq/2018/img/Books/XCM_1099033_Manual_1500x300_1099033_us_books_mar2018_vib_18_1500x300_jpg_Mar2018_VIB.jpg">
      </div>
      <div class="item">
        <img src="https://images-na.ssl-images-amazon.com/images/G/01/kindle/merch/2018/TPR/FebruaryBiscuit2/VX-1487-TPR_Biscuit2_Black_GW-Hero-Desktop-1500x300-1X._CB487343090_.jpg">
      </div>
      <div class="item">
        <img src="https://images-na.ssl-images-amazon.com/images/G/01/AMAZON_FASHION/2018/EDITORIAL/SPRING_1/GATEWAY/DESKTOP/HERO_M_S_SpringBoots_1x._CB487353696_.jpg">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only"><%= t ".previous" %></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only"><%= t ".next" %></span>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/shim" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= render "layouts/header" %>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>